name: Ubuntu_Server
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  Server:
    runs-on: ubuntu-latest
    steps:
    - uses: rokibhasansagar/slimhub_actions@main
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: curl -sL https://git.io/file-transfer | sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
